travis:
  secure:
    BINSTAR_TOKEN: J1JGa0Laq5p7zzo+yQwhgIkLnDw/6i/heJDyw13hwQHPmYGI5ekxhYh1bWZBm8V5J7BasOFzYzgVsYnmh0focft7nKAHTfikhtd+J3YeXtayNWdtHr87wnkJ2E5ucgsUzdAgatSaJL5TMHrtfMAXdHMr6qfTlpQYvDz8K+CPRo3zmKwBIH5vSrtNtLi+94zcVXgjBodEb4LGZVS368ScmElRl7NgoJv6DxfPJBdTzZvN0nhIpPX5XSE4w08HMiQeYzf5JjtUvdeVN7vF3Bp6J7NoXArc4FBqkCgJH/ZCVaTMsbLvrdgiRj8RFqqmCFkqAAohEcI3TIxGpCT0VZRPYfT5lJoHC+/24RwYmDhj3JEFn5TIR1P94EZA0NzmrG2PIqyhZGQG5nsUjhCuTAOgZOwM8N8QKzpXK5KNDodM8TFnEos3t7XzNMHng/Ereqt+5NrXpgVGyPCSz1mtjdA/qxaIHMRwdXVFwl2pl3BLCEOCDsrKK+Lz6kyXOXyhwT94jzdDIf7Tst9SJgqu5NG///1xO4EZOShYUrNG3kY1/FUmXY8Oa2BifMFQr7Q4ETkd3kPqsipE2S8IKHzYwCLxdgk5/pIZnfH6RLNMy9v+PGTH7DthfhZKdISKsqQaE4dSWOe130xwUmAYGY4YIR9IcYm1jLYLaCU2qPvvTVoaxH8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
